### ISSUE TITLE
Compatibility 2023.2

### ISSUE THREAD

**Issue by No3x** [dmfs/unclutter-java#5]
Can you please add 2023.2 compatibility to the plugin?

**Comment by dmfs** [comment]
I've published version 0.13.0. As usual, this should be available within 2 business days.

**Comment by No3x** [comment]
Thanks for your effort.

**Comment by dmfs** [comment]
I accidentally broke compatibility with Intellij < 2023.1. I've uploaded version 0.13.1. Not sure if 0.13.0 gets approved with this issue.

**Comment by dmfs** [comment]
0.13.1 is available now
